name: Tag and Release

on:
  push:
    branches: [main]

jobs:
  tag-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # 1️⃣ Calculate next SemVer tag
      - id: bump
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          default_bump: false
          release_branches: main

      # 2️⃣ Generate release notes from commits
      - name: Generate release notes
        id: notes
        run: |
          RELEASE_NOTES=$(git log --pretty=format:"- %s (%an)" $(git describe --tags --abbrev=0)..HEAD)
          RELEASE_NOTES="${RELEASE_NOTES//'%'/'%25'}"
          RELEASE_NOTES="${RELEASE_NOTES//$'\n'/'%0A'}"
          RELEASE_NOTES="${RELEASE_NOTES//$'\r'/'%0D'}"
          echo "release_notes=$RELEASE_NOTES" >> $GITHUB_OUTPUT

      # 3️⃣ Update CHANGELOG.md with new section
      - name: Update CHANGELOG.md
        uses: stefanzweifel/changelog-updater-action@v1
        with:
          latest-version: ${{ steps.bump.outputs.new_tag }}
          path-to-changelog: CHANGELOG.md
          compare-url-target-revision: HEAD
          parse-github-usernames: false
          release-notes: ${{ steps.notes.outputs.release_notes }}

      # 4️⃣ Commit and push updated CHANGELOG.md
      - name: Commit updated CHANGELOG
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add CHANGELOG.md
          git commit -m "chore: update changelog for ${{ steps.bump.outputs.new_tag }}"
          git push origin main

      # 5️⃣ Create GitHub Release
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.bump.outputs.new_tag }}
          name: Release ${{ steps.bump.outputs.new_tag }}
          body_path: CHANGELOG.md
